spring:
  application:
    name: app-worker

app:
  easycache:
    host: ${EASYCACHE_HOST:localhost}
    port: ${EASYCACHE_PORT:6379}
    password: ${EASYCACHE_PASSWORD:}
    timeout: ${EASYCACHE_TIMEOUT:2000}
    pool:
      max-total: ${EASYCACHE_POOL_MAX_TOTAL:16}
      max-idle: ${EASYCACHE_POOL_MAX_IDLE:8}
      min-idle: ${EASYCACHE_POOL_MIN_IDLE:0}
  rabbit:
    enabled: true
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  security:
    enabled: ${APP_SECURITY_ENABLED:true}
