spring:
  config:
    activate:
      on-profile: local-noinfra
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - sgw.common.persistence.config.PersistenceAutoConfiguration
      - sgw.common.infra.config.EasyCacheConfiguration
      - sgw.common.infra.config.RabbitConfiguration
      - sgw.common.infra.config.MinioConfiguration
  batch:
    job:
      enabled: false
app:
  datasource:
    enabled: false
management:
  health:
    defaults:
      enabled: false
