spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql-db:3306/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:app}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${API_HTTP_PORT:8080}
