server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: app-api
  batch:
    job:
      enabled: false
app:
  egov:
    enabled: ${EGOV_ENABLED:false}
  security:
    enabled: ${APP_SECURITY_ENABLED:true}
